#!/usr/bin/env python3
"""PreToolUse(Edit|Write) — guard the test suite from being "fixed" instead of the code.

v6 rewrite. The v5 shell version blocked with exit 2, which had two failure modes found in
real use:

  * TDD was impossible. Creating a test with Write was allowed, but EVERY later Edit of that
    same file was hard-blocked — so the red→green loop could never run. v6 never blocks a file
    the agent created in this session (tracked in .claude/state/), and asks instead of refusing.
  * No escape hatch. A legitimate test refactor had to be done outside Claude Code. v6 emits
    `permissionDecision: "ask"` — the user decides in one keystroke — and honours
    CMK_ALLOW_TEST_EDITS=1 for a deliberate test-maintenance session.

The rule it enforces is unchanged and is the point of the hook: a failing test means the CODE
is wrong, not the test.

v7.1 (protect-tests v2): an existing test file asks ONLY when the change can weaken what the test
proves — an Edit whose `old_string` holds a line with an assertion/skip token that `new_string`
no longer has (`toBe(5)` → `toBe(6)`, a deleted `assert`), a `new_string` that adds a skip/only
marker (`it` → `it.skip`), or a Write whose new content fails the same rule against the file on
disk. Pure additions, renames outside assertions and fixture edits pass silently. A `.snap`
file is never parsed for tokens, but any Edit/Write to one asks — snapshots are regenerated by
the test runner, not written by hand.

Output: nothing (no opinion — the normal permission flow decides) or {"hookSpecificOutput": {"hookEventName": "PreToolUse",
                                "permissionDecision": "ask",
                                "permissionDecisionReason": "..."}}
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

TEST_PATH_RE = re.compile(
    r"(^|/)test_[^/]+\.py$"      # Python: test_foo.py
    r"|(^|/)[^/]+_test\.py$"     # Python: foo_test.py
    r"|(^|/)[^/]+_test\.go$"     # Go
    r"|/__tests__/"              # JS/TS convention
    r"|(^|/)tests?/"             # a tests/ or test/ directory segment
    r"|\.test\."                 # foo.test.ts
    r"|\.spec\."                 # foo.spec.ts
)

# Not code, never guarded — fixtures, docs and data under a tests/ dir are ordinary files.
# `.snap` is exempt from the token rules below but has its own rule (any hand edit asks).
EXEMPT_SUFFIXES = {".md", ".txt", ".json", ".yaml", ".yml", ".csv", ".snap", ".fixture"}

# A line holding one of these proves (or skips) something; losing it can weaken the test.
ASSERT_TOKENS = (
    "expect(", "assert", "toBe", "toEqual", "toThrow", ".not.", "pytest.raises", "self.assert",
    ".skip", "xit(", "xdescribe", "@pytest.mark.skip", "t.Skip",
)
# Adding one of these turns a test off (or turns every other test off).
SKIP_RE = re.compile(
    r"\.skip\b|\.only\b|\bxit\b|@pytest\.mark\.skip|\bt\.Skip|\btest\.todo\b"
)


def allow() -> None:
    # No opinion = exit 0 with NO output. A `permissionDecision: "allow"` here would skip the user's
    # permission prompt for every non-test Edit/Write (v6.0-7.0.3 did exactly that: in default mode the
    # kit silently auto-approved all edits — found 2026-09-26 by a headless probe).
    sys.exit(0)


def ask(reason: str) -> None:
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "ask",
            "permissionDecisionReason": reason,
        }
    }))
    sys.exit(0)


def session_created_file(project_dir: Path, session_id: str, file_path: str) -> bool:
    """Files this session created are its own to iterate on — that is the TDD loop."""
    ledger = project_dir / ".claude" / "state" / f"{session_id}_created_tests"
    if not ledger.exists():
        return False
    try:
        return file_path in ledger.read_text(encoding="utf-8").splitlines()
    except OSError:
        return False


def remember_created(project_dir: Path, session_id: str, file_path: str) -> None:
    ledger = project_dir / ".claude" / "state" / f"{session_id}_created_tests"
    try:
        ledger.parent.mkdir(parents=True, exist_ok=True)
        with ledger.open("a", encoding="utf-8") as fh:
            fh.write(file_path + "\n")
    except OSError:
        pass


def weakening(old: str, new: str) -> str:
    """Why replacing `old` with `new` can weaken a test, or "" when it cannot.

    (1) a line of `old` carrying an assertion/skip token is no longer a line of `new`;
    (2) `new` carries more skip/only markers than `old`.
    Lines compare stripped, so re-indentation alone is not a change.
    """
    new_lines = {ln.strip() for ln in new.splitlines()}
    for line in old.splitlines():
        text = line.strip()
        if text and any(tok in text for tok in ASSERT_TOKENS) and text not in new_lines:
            return f"an assertion line changes or disappears: `{text[:120]}`"
    added = len(SKIP_RE.findall(new)) - len(SKIP_RE.findall(old))
    if added > 0:
        return "it adds a skip/only marker (`.skip`, `.only`, `xit`, `@pytest.mark.skip`, `t.Skip`, `test.todo`)"
    return ""


def main() -> None:
    if os.environ.get("CMK_ALLOW_TEST_EDITS") == "1":
        allow()

    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except (json.JSONDecodeError, ValueError):
        allow()
        return

    tool_input = payload.get("tool_input") or {}
    file_path = str(tool_input.get("file_path") or "")
    if not file_path:
        allow()

    suffix = Path(file_path).suffix.lower()
    if suffix == ".snap":
        ask(
            f"{file_path} is a test snapshot. Snapshots are regenerated by the test runner "
            "(`-u` / `--update-snapshot`) after the code change is accepted, not written by hand — "
            "confirm only if this edit is deliberate. Set CMK_ALLOW_TEST_EDITS=1 for a whole session of test work."
        )
    if suffix in EXEMPT_SUFFIXES:
        allow()
    if not TEST_PATH_RE.search(file_path):
        allow()

    project_dir = Path(os.environ.get("CLAUDE_PROJECT_DIR", Path.cwd()))
    session_id = re.sub(r"[^A-Za-z0-9_-]", "", str(payload.get("session_id") or "unknown")) or "unknown"

    # A new test file, or one this session authored: the red→green loop, always allowed.
    if not Path(file_path).exists():
        remember_created(project_dir, session_id, file_path)
        allow()
    if session_created_file(project_dir, session_id, file_path):
        allow()

    # v2: an existing test file asks only when the change can weaken what it proves.
    tool = payload.get("tool_name")
    if tool == "Write":
        try:
            old = Path(file_path).read_text(encoding="utf-8", errors="replace")
        except OSError:
            old = None
        reason = weakening(old, str(tool_input.get("content") or "")) if old is not None else (
            "the file on disk could not be read to compare"
        )
    else:
        reason = weakening(str(tool_input.get("old_string") or ""), str(tool_input.get("new_string") or ""))
    if not reason:
        allow()

    ask(
        f"{file_path} is an existing test file and {reason}. A failing test usually means the CODE "
        "is wrong, not the test — confirm only if this is deliberate test maintenance (a spec whose "
        "expectation genuinely changed). Set CMK_ALLOW_TEST_EDITS=1 for a whole session of test work."
    )


if __name__ == "__main__":
    main()
